name: Node Build en test

on: 
  push:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        node-version: [16.x]
        on: [ubuntu.latest,windows-latest]

steps:
  - uses: actions/checkout@v2
  - name: use NOde.js ${{matrix.node-version}}
  - uses: actions/setup-node@v1
    with: 
      node-version: ${{matrix.node-version}}
  - run: npm ci //clean install
  - run: npm test
  - run: npm run build
